[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agro_dao = "CRAooBpTSWbr3m5YKm2cEWAQcHgqqARmZXYj5Z1RSsX2"
research_dao = "7eXMy1pAPuwGFSpRJA1YBmfQq7u2wxs27g7ko23VcxxD"
reputation_dao = "HtzmTdZL8j5VSSDMSPYpwvHZLNCbP2b27KNxHzHi52Bw"
treasury_dao = "7jdb4RV2Wep32dBgAoprWvHTqKaCN9d6XWQ4NGtUbBpq"
governance_dao = "FGmtS6VD6rhP9k8meqnYoT2w2txRfzTQB8DeXDcoxzaR"

[programs.devnet]
agro_dao = "5tBzz5Fi88JKejLdDx9XsWHyvwdMimQjvShwpR2mgKgU"
research_dao = "DF1y7PHHo7ekNEKztCMTDsZ3TrYdLAhgBCFQPzoi3PHw"
reputation_dao = "HtzmTdZL8j5VSSDMSPYpwvHZLNCbP2b27KNxHzHi52Bw"
treasury_dao = "9cDozwVvb4EHtzVwtbseAkuWRXjPfSmhuoiLiVK8yMY8"
governance_dao = "FGmtS6VD6rhP9k8meqnYoT2w2txRfzTQB8DeXDcoxzaR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20000
shutdown_wait = 5000
upgradeable = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
