[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agro_dao = "HWjwngNibn1coAzqLZhg4huw5pH5gNZY8zxJaK7s3Hbj"
research_dao = "FUpDQNRZyx2u8uEnerDP9Y6gRT4HUaTZcU7ViziYxWQp"
reputation_dao = "WZ13w2w964gyDhpd3GWpFuCJQWYaGNAgybt3rrrUuxD"
treasury_dao = "BT9K4n1w56VP6pL9fAwZesLCJWJ9rmaJ2d3XZxGuGkYB"
governance_dao = "DyazGQj7kUgXoSxcReQk1cDfRQ9QJhQaZRs3C2NXgVMy"

[programs.devnet]
agro_dao = "HWjwngNibn1coAzqLZhg4huw5pH5gNZY8zxJaK7s3Hbj"
research_dao = "FUpDQNRZyx2u8uEnerDP9Y6gRT4HUaTZcU7ViziYxWQp"
reputation_dao = "WZ13w2w964gyDhpd3GWpFuCJQWYaGNAgybt3rrrUuxD"
treasury_dao = "BT9K4n1w56VP6pL9fAwZesLCJWJ9rmaJ2d3XZxGuGkYB"
governance_dao = "DyazGQj7kUgXoSxcReQk1cDfRQ9QJhQaZRs3C2NXgVMy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./my-keypair.json"

[test]
startup_wait = 20000
shutdown_wait = 5000
upgradeable = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
