[package]
name = "treasury-dao"
version = "0.1.0"
description = "Treasury and funding management for the AgroDAO ecosystem"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "treasury_dao"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
default = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
